# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: "%kernel.cache_dir%/flysystem"
        s3_adapter:
            awss3v3:
                client: "s3_client"
                bucket: "%env(AWS_S3_BUCKET)%"
        console_adapter:
            local:
                location: "%kernel.project_dir%/src/Command/Assets"
    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
        s3:
            adapter: s3_adapter
        console:
            adapter: console_adapter
